[package]
name = "devobox"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0"
clap = { version = "4.5", features = ["derive"] }
shellexpand = "3.1"
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.9"
